# Milestone 2: Model Building

**Objective:**  
Develop and train a recommendation model using collaborative filtering.

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
user_item_matrix = pd.read_csv(
    "../Milestone_1/user_item_matrix.csv",
    index_col=0
)

user_item_matrix.head()

,10002,10080,10120,10123C,10124A,10124G,10125,10133,10135,11001,...,90214V,90214W,90214Y,90214Z,BANK CHARGES,C2,DOT,M,PADS,POST
user_id,,,,,,,,,,,,,,,,,,,,,
12346,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12347,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12348,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
12349,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12350,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [4]:
user_similarity = cosine_similarity(user_item_matrix)

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)

user_similarity_df.head()

user_id,12346,12347,12348,12349,12350,12352,12353,12354,12355,12356,...,18273,18274,18276,18277,18278,18280,18281,18282,18283,18287
user_id,,,,,,,,,,,,,,,,,,,,,
12346,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
12347,0.0,1.000000,0.148879,0.020750,0.014435,0.028933,0.0,0.023478,0.506252,0.186107,...,0.0,0.001212,0.406837,0.0,0.015133,0.037236,0.0,0.010873,0.074510,0.108942
12348,0.0,0.148879,1.000000,0.000169,0.000315,0.001311,0.0,0.010634,0.286226,0.226244,...,0.0,0.032510,0.168665,0.0,0.000000,0.000000,0.0,0.000000,0.175170,0.110096
12349,0.0,0.020750,0.000169,1.000000,0.030121,0.131151,0.0,0.004931,0.000180,0.150819,...,0.0,0.148066,0.000000,0.0,0.015680,0.000000,0.0,0.013398,0.065295,0.022576
12350,0.0,0.014435,0.000315,0.030121,1.000000,0.001610,0.0,0.000000,0.000000,0.001179,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.019385,0.000000

In [5]:
def recommend_products(user_id, top_n=5):
    if user_id not in user_item_matrix.index:
        return "User not found"

    # Step 1: Find similar users
    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:6]

    # Step 2: Compute weighted product scores
    weighted_scores = user_item_matrix.loc[similar_users.index].T.dot(similar_users)

    # Step 3: Remove products already purchased by user
    user_purchases = user_item_matrix.loc[user_id]
    weighted_scores = weighted_scores[user_purchases == 0]

    # Step 4: Return top N recommendations
    return weighted_scores.sort_values(ascending=False).head(top_n)

In [6]:
sample_user = user_item_matrix.index[0]

print("Recommendations for user:", sample_user)
recommend_products(sample_user)

Recommendations for user: 12346

23167    40.539751
21401    38.739106
21400    38.739106
22962    27.649278
47566    23.809101
dtype: float64